apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.4
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HTTP_RELATIVE_PATH
              value: /keycloak
            - name: KEYCLOAK_FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KEYCLOAK_URL
            - name: KC_PROXY
              value: edge
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
          livenessProbe:
            httpGet:
              path: /keycloak/
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /keycloak/
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
