FROM nginx:alpine

# Usuń domyślną konfigurację
RUN rm /etc/nginx/conf.d/default.conf

# Skopiuj własny plik konfiguracyjny
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Skopiuj zbudowany frontend
COPY build /usr/share/nginx/html
