FROM node:18

WORKDIR /app

# Skopiuj package.json i zainstaluj zależności
COPY package*.json ./
RUN npm install --production

# Skopiuj kod aplikacji
COPY . .

# Ustaw domyślny plik wejściowy
CMD ["node", "src/app.js"]
